SneakerWorld/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Password;

    /**
     * @ORM\OneToMany(targetEntity=CommentSneaker::class, mappedBy="id_user")
     */
    private $comment_sneaker;

    /**
     * @ORM\Column(type="string")
     */
    private $roles = 'ROLE_USER';


    public function __construct()
    {
        $this->comment_sneaker = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(?string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }


    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(?string $Password): self
    {
        $this->Password = $Password;

        return $this;
    }

    /**
     * @return Collection|CommentSneaker[]
     */
    public function getCommentSneaker(): Collection
    {
        return $this->comment_sneaker;
    }

    public function addCommentSneaker(CommentSneaker $commentSneaker): self
    {
        if (!$this->comment_sneaker->contains($commentSneaker)) {
            $this->comment_sneaker[] = $commentSneaker;
            $commentSneaker->setIdUser($this);
        }

        return $this;
    }

    public function removeCommentSneaker(CommentSneaker $commentSneaker): self
    {
        if ($this->comment_sneaker->removeElement($commentSneaker)) {
            // set the owning side to null (unless already changed)
            if ($commentSneaker->getIdUser() === $this) {
                $commentSneaker->setIdUser(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $role = [];
        $role[] = $roles;

        return array_unique($role);

    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        // TODO: Implement getUsername() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function setRoles(string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }


}

SneakerWorld/src/Form/CommentType.php
<?php

namespace App\Form;

use App\Entity\CommentSneaker;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('commentaire', TextType::class, array(
                'label'   => false,
                'attr' => array(
                    'placeholder' => 'Entrez votre commentaire ...'
                )
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CommentSneaker::class,
        ]);
    }
}

SneakerWorld/src/Controller/CommentController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use App\Form\CommentType;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\CommentSneaker;
use App\Entity\Sneaker;

class CommentController extends AbstractController
{

    /**
     * @Route("{_locale}/commentAdd{id}", name="comment.sneaker")
     * @param Request $request
     * @param Sneaker $sneaker
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function getComment(Sneaker $sneaker, Request $request, EntityManagerInterface $em ): Response
    {
        $comments = $sneaker->getCommentSneaker();
        $comment = new CommentSneaker();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setIdUser($this->getUser());
            $comment->setPrenom($this->getUser()->getPrenom());
            $comment->setIdSneaker($sneaker);
            $em->persist($comment);
            $em->flush();
            return $this->redirect($this->generateUrl('sneaker'));
        }
        return $this->render('comment/index.html.twig', [
            'comments' => $comments,
            'sneaker' => $sneaker,
            'form' => $form->createView(),
        ]);
    }
}

SneakerWorld/templates/comment/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div style="margin: 0 65px 0 65px;">

  {% include './/common/header.html.twig' %}

    <br><br>
    <div class="container">
        <div class="row">
            <div class="d-flex justify-content-center">
                <div class="card" style="margin: 0 0 65px 0;">
                    <img class="card-img-top" src="{{ asset('uploads/image/' ~ sneaker.image) }}" alt="{{ sneaker.nom }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ sneaker.nom }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ sneaker.likeSneakers | length }} {{ 'common.ontlike'|trans }}</h6>
                        <h5 class="card-text">{{ sneaker.price }}€</h5>
                        <p class="card-text"> {{ 'common.listecomm'|trans }} :</p>
                        {% for comment in comments %}
                            <p><b>{{ comment.prenom }} dit : </b><br> {{ comment.commentaire }}</p>

                        {% endfor %}
                        {{ form_start(form) }}
                        {{ form_row(form) }}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary" href="{{ path('comment.sneaker', {id:sneaker.id}) }}" >{{ 'common.enregistrer'|trans }}</button>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock %}